version: "3.1"
services:
  wordpress:
    image: wordpress
    restart: always
    volumes:
      - "./:/var/www/html/wp-content/plugins/clinked-wordpress-plugin"
    ports:
      - 8080:80
    environment:
      WORDPRESS_DEBUG: true
      WORDPRESS_DB_HOST: 172.23.0.2
      WORDPRESS_DB_USER: root
      WORDPRESS_DB_PASSWORD: example
    networks:
      vpcbr:
        ipv4_address: 172.23.0.3

  mysql:
    image: mysql:5.7
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: example
      MYSQL_DATABASE: wordpress
    networks:
      vpcbr:
        ipv4_address: 172.23.0.2      

networks:
  vpcbr:
    driver: bridge
    ipam:
     config:
       - subnet: 172.23.0.0/16
